import { google } from 'googleapis';
import type { AppConfig } from '../config.js';
import type { LikedVideo, PlaylistWithVideos, Subscription, Video } from '../domain.js';
import { normalizeLikedVideo, normalizePlaylist, normalizeSubscription, normalizeVideo, playlistWithVideos } from './normalize.js';
export const YOUTUBE_READ_SCOPE = 'https://www.googleapis.com/auth/youtube.readonly';
export class YouTubeApiError extends Error { constructor(public readonly kind:'quota'|'auth'|'upstream'|'malformed', message:string) { super(message); } }
export function createOAuthClient(config: AppConfig) { if (!config.googleClientId || !config.googleClientSecret) throw new Error('OAuth is not configured.'); return new google.auth.OAuth2(config.googleClientId,config.googleClientSecret,config.googleRedirectUri); }
export function createYouTubeClient(auth?: string | ReturnType<typeof createOAuthClient>) { return google.youtube({version:'v3',auth}); }
function apiError(error:unknown):YouTubeApiError { const status=(error as {code?:number})?.code; if(status===401||status===403) return new YouTubeApiError(status===403?'quota':'auth','YouTube authorization or quota request failed.'); return new YouTubeApiError('upstream','YouTube API request failed.'); }
export async function allPages<T>(load:(pageToken?:string)=>Promise<{items?:T[]|null;nextPageToken?:string|null}>):Promise<T[]> { const results:T[]=[]; let token: string|undefined; const seen=new Set<string>(); try { do { if(token && seen.has(token)) throw new YouTubeApiError('malformed','YouTube returned a repeated pagination token.'); if(token)seen.add(token); const page=await load(token); results.push(...(page.items??[])); token=page.nextPageToken??undefined; } while(token); return results; } catch(error) { if(error instanceof YouTubeApiError) throw error; throw apiError(error); } }
export async function getPublicVideos(apiKey:string, ids:string[]):Promise<Video[]> { if(!ids.length)return []; const api=createYouTubeClient(apiKey); const items=await allPages((pageToken)=>api.videos.list({part:['snippet'],id:ids,maxResults:50,pageToken}).then(r=>r.data)); return items.map(normalizeVideo).filter((v):v is Video=>Boolean(v)); }
export async function fetchSubscriptions(auth:ReturnType<typeof createOAuthClient>):Promise<Subscription[]> { const api=createYouTubeClient(auth); const items=await allPages((pageToken)=>api.subscriptions.list({part:['snippet'],mine:true,maxResults:50,pageToken}).then(r=>r.data)); return items.map(normalizeSubscription).filter((v):v is Subscription=>Boolean(v)); }
export async function fetchLikedVideos(auth:ReturnType<typeof createOAuthClient>):Promise<LikedVideo[]> { const api=createYouTubeClient(auth); const channel=await api.channels.list({part:['contentDetails'],mine:true}).catch((e)=>{throw apiError(e);}); const id=channel.data.items?.[0]?.contentDetails?.relatedPlaylists?.likes; if(!id)return []; const items=await allPages((pageToken)=>api.playlistItems.list({part:['snippet'],playlistId:id,maxResults:50,pageToken}).then(r=>r.data)); return items.map(normalizeLikedVideo).filter((v):v is LikedVideo=>Boolean(v)); }
export async function fetchPlaylists(auth:ReturnType<typeof createOAuthClient>):Promise<PlaylistWithVideos[]> { const api=createYouTubeClient(auth); const rows=await allPages((pageToken)=>api.playlists.list({part:['snippet'],mine:true,maxResults:50,pageToken}).then(r=>r.data)); const playlists=rows.map(normalizePlaylist).filter((v):v is NonNullable<typeof v>=>Boolean(v)); return Promise.all(playlists.map(async (playlist)=>{const items=await allPages((pageToken)=>api.playlistItems.list({part:['snippet'],playlistId:playlist.id,maxResults:50,pageToken}).then(r=>r.data));return playlistWithVideos(playlist,items);})); }
export async function fetchAuthenticatedIdentity(auth:ReturnType<typeof createOAuthClient>):Promise<{subject:string;displayName?:string}> { const api=createYouTubeClient(auth); try { const response=await api.channels.list({part:['id','snippet'],mine:true}); const item=response.data.items?.[0]; if(!item?.id) throw new YouTubeApiError('malformed','No YouTube channel is associated with this account.'); return {subject:`youtube:${item.id}`,displayName:item.snippet?.title??undefined}; } catch(error) { if(error instanceof YouTubeApiError)throw error; throw apiError(error); } }
