import type { youtube_v3 } from 'googleapis';
import type { Channel, LikedVideo, Playlist, PlaylistWithVideos, Subscription, Video } from '../domain.js';
const thumbnail = (snippet: youtube_v3.Schema$VideoSnippet | youtube_v3.Schema$ChannelSnippet | youtube_v3.Schema$PlaylistSnippet | undefined) => snippet?.thumbnails?.high?.url ?? snippet?.thumbnails?.medium?.url ?? snippet?.thumbnails?.default?.url ?? undefined;
export function normalizeVideo(item: youtube_v3.Schema$Video): Video | undefined { const s=item.snippet; if (!item.id || !s?.title) return undefined; return { id:item.id,title:s.title,channelId:s.channelId??undefined,channelTitle:s.channelTitle??undefined,thumbnailUrl:thumbnail(s),description:s.description??undefined,publishedAt:s.publishedAt??undefined }; }
export function normalizeSubscription(item: youtube_v3.Schema$Subscription): Subscription | undefined { const s=item.snippet; const id=s?.resourceId?.channelId; if (!id || !s?.title) return undefined; return { channel:{id,title:s.title,thumbnailUrl:thumbnail(s)},subscribedAt:s.publishedAt??undefined }; }
export function normalizePlaylist(item: youtube_v3.Schema$Playlist): Playlist | undefined { const s=item.snippet; if (!item.id || !s?.title) return undefined; return { id:item.id,title:s.title,description:s.description??undefined,thumbnailUrl:thumbnail(s),publishedAt:s.publishedAt??undefined }; }
export function normalizeLikedVideo(item: youtube_v3.Schema$PlaylistItem): LikedVideo | undefined { const s=item.snippet; const videoId=s?.resourceId?.videoId; if (!videoId || !s?.title) return undefined; return { likedAt:s.publishedAt??undefined,video:{id:videoId,title:s.title,channelId:s.videoOwnerChannelId ?? s.channelId ?? undefined,channelTitle:s.videoOwnerChannelTitle ?? s.channelTitle ?? undefined,thumbnailUrl:thumbnail(s),description:s.description??undefined,publishedAt:s.publishedAt??undefined} }; }
export function playlistWithVideos(playlist: Playlist, items: youtube_v3.Schema$PlaylistItem[]): PlaylistWithVideos { return { playlist, videos: items.map(normalizeLikedVideo).filter((v):v is LikedVideo=>Boolean(v)).map((v)=>v.video) }; }
export function normalizeChannel(item: youtube_v3.Schema$Channel): Channel | undefined { const s=item.snippet; if(!item.id||!s?.title)return undefined; return {id:item.id,title:s.title,thumbnailUrl:thumbnail(s)}; }
