import { Pool } from 'pg';
import type { Channel, IngestionRepository, LikedVideo, OAuthAccount, PlaylistWithVideos, Subscription, User, Video } from '../domain.js';

export class PostgresRepository implements IngestionRepository {
  readonly pool: Pool;
  constructor(databaseUrl: string) { this.pool = new Pool({ connectionString: databaseUrl }); }
  async close() { await this.pool.end(); }
  async upsertUser(user: User) { await this.pool.query(`INSERT INTO users(id,google_subject,display_name) VALUES($1,$2,$3) ON CONFLICT(google_subject) DO UPDATE SET display_name=EXCLUDED.display_name,updated_at=now()`, [user.id, user.googleSubject, user.displayName]); return user; }
  async saveOAuthAccount(userId: string, account: OAuthAccount) { await this.pool.query(`INSERT INTO oauth_accounts(user_id,provider_account_id,encrypted_access_token,encrypted_refresh_token,access_token_expires_at,scope) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id) DO UPDATE SET encrypted_access_token=EXCLUDED.encrypted_access_token,encrypted_refresh_token=COALESCE(EXCLUDED.encrypted_refresh_token,oauth_accounts.encrypted_refresh_token),access_token_expires_at=EXCLUDED.access_token_expires_at,scope=EXCLUDED.scope,updated_at=now()`, [userId, account.providerAccountId, account.encryptedAccessToken, account.encryptedRefreshToken, account.accessTokenExpiresAt, account.scope]); }
  async replaceSubscriptions(userId: string, values: Subscription[]) { const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('DELETE FROM subscriptions WHERE user_id=$1', [userId]); for (const value of unique(values, (v) => v.channel.id)) { await upsertChannel(client, value.channel); await client.query('INSERT INTO subscriptions(user_id,channel_id,subscribed_at) VALUES($1,$2,$3)', [userId, value.channel.id, value.subscribedAt]); } await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async replaceLikedVideos(userId: string, values: LikedVideo[]) { const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('DELETE FROM liked_videos WHERE user_id=$1', [userId]); for (const value of unique(values, (v) => v.video.id)) { await upsertVideo(client, value.video); await client.query('INSERT INTO liked_videos(user_id,video_id,liked_at) VALUES($1,$2,$3)', [userId, value.video.id, value.likedAt]); } await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async replacePlaylists(userId: string, values: PlaylistWithVideos[]) { const client = await this.pool.connect(); try { await client.query('BEGIN'); await client.query('DELETE FROM youtube_playlists WHERE user_id=$1', [userId]); for (const { playlist, videos } of unique(values, (v) => v.playlist.id)) { await client.query(`INSERT INTO youtube_playlists(id,user_id,title,description,thumbnail_url,published_at) VALUES($1,$2,$3,$4,$5,$6)`, [playlist.id,userId,playlist.title,playlist.description,playlist.thumbnailUrl,playlist.publishedAt]); for (const [position, video] of unique(videos, (v) => v.id).entries()) { await upsertVideo(client, video); await client.query('INSERT INTO playlist_videos(playlist_id,video_id,position) VALUES($1,$2,$3)', [playlist.id, video.id, position]); } } await client.query('COMMIT'); } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
  async getUser(id: string) { const { rows } = await this.pool.query('SELECT id,google_subject,display_name FROM users WHERE id=$1',[id]); return rows[0] ? { id: rows[0].id, googleSubject: rows[0].google_subject, displayName: rows[0].display_name ?? undefined } : undefined; }
  async getSubscriptions(id: string) { const { rows } = await this.pool.query('SELECT c.id,c.title,c.thumbnail_url,s.subscribed_at FROM subscriptions s JOIN youtube_channels c ON c.id=s.channel_id WHERE s.user_id=$1 ORDER BY c.title',[id]); return rows.map((r) => ({ channel: channel(r), subscribedAt: iso(r.subscribed_at) })); }
  async getLikedVideos(id: string) { const { rows } = await this.pool.query('SELECT v.*,l.liked_at FROM liked_videos l JOIN youtube_videos v ON v.id=l.video_id WHERE l.user_id=$1 ORDER BY l.liked_at DESC NULLS LAST',[id]); return rows.map((r) => ({ video: video(r), likedAt: iso(r.liked_at) })); }
  async getPlaylists(id: string) { const { rows } = await this.pool.query('SELECT id,title,description,thumbnail_url,published_at FROM youtube_playlists WHERE user_id=$1 ORDER BY title',[id]); return Promise.all(rows.map(async (r) => { const videos = await this.pool.query('SELECT v.* FROM playlist_videos pv JOIN youtube_videos v ON v.id=pv.video_id WHERE pv.playlist_id=$1 ORDER BY pv.position',[r.id]); return { playlist: { id:r.id,title:r.title,description:r.description??undefined,thumbnailUrl:r.thumbnail_url??undefined,publishedAt:iso(r.published_at) }, videos: videos.rows.map(video) }; })); }
}
const unique = <T>(values:T[], key:(value:T)=>string) => [...new Map(values.map((value)=>[key(value),value])).values()];
async function upsertChannel(client:any, c:Channel) { await client.query('INSERT INTO youtube_channels(id,title,thumbnail_url) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,thumbnail_url=EXCLUDED.thumbnail_url,updated_at=now()',[c.id,c.title,c.thumbnailUrl]); }
async function upsertVideo(client:any, v:Video) { if (v.channelId && v.channelTitle) await upsertChannel(client,{id:v.channelId,title:v.channelTitle,thumbnailUrl:undefined}); await client.query('INSERT INTO youtube_videos(id,title,channel_id,channel_title,thumbnail_url,description,published_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,channel_id=EXCLUDED.channel_id,channel_title=EXCLUDED.channel_title,thumbnail_url=EXCLUDED.thumbnail_url,description=EXCLUDED.description,published_at=EXCLUDED.published_at,updated_at=now()',[v.id,v.title,v.channelId,v.channelTitle,v.thumbnailUrl,v.description,v.publishedAt]); }
const iso=(value:Date|string|null)=>value ? new Date(value).toISOString() : undefined;
const channel=(r:any):Channel=>({id:r.id,title:r.title,thumbnailUrl:r.thumbnail_url??undefined});
const video=(r:any):Video=>({id:r.id,title:r.title,channelId:r.channel_id??undefined,channelTitle:r.channel_title??undefined,thumbnailUrl:r.thumbnail_url??undefined,description:r.description??undefined,publishedAt:iso(r.published_at)});
