import crypto from 'node:crypto'; import express, { type NextFunction, type Request, type Response } from 'express';
import { config } from './config.js'; import type { IngestionRepository } from './domain.js'; import { MemoryRepository } from './db/memory-repository.js'; import { PostgresRepository } from './db/postgres-repository.js';
import { sessionUserId } from './auth/session.js'; import { demoUser } from './fixtures/demo-data.js'; import { ingestYouTubeUser } from './ingestion/service.js'; import { capabilities } from './youtube/capabilities.js'; import { createOAuthClient, YOUTUBE_READ_SCOPE } from './youtube/client.js';
const app=express(); const pending=new Set<string>(); const repository:IngestionRepository=config.demoMode?new MemoryRepository():config.databaseUrl?new PostgresRepository(config.databaseUrl):(()=>{throw new Error('DATABASE_URL is required unless DEMO_MODE=true.');})();
function userId(request:Request) { return sessionUserId(request.headers.cookie); }
async function requireUser(request:Request,response:Response,next:NextFunction) { const id=config.demoMode?demoUser.id:userId(request); if(!id || !await repository.getUser(id)) return response.status(401).json({error:'Authentication required.'}); response.locals.userId=id; next(); }
function setUserCookie(response:Response,id:string) { response.cookie('yir_user',id,{httpOnly:true,sameSite:'lax',secure:config.cookieSecure,path:'/'}); }
app.get('/health',(_req,res)=>res.json({status:'ok',phase:1,demoMode:config.demoMode})); app.get('/capabilities',(_req,res)=>res.json({capabilities}));
app.get('/auth/google',(_req,res)=>{ if(config.demoMode)return res.status(409).json({error:'OAuth is disabled in demo mode; use fixture endpoints.'}); if(!config.googleClientId||!config.googleClientSecret)return res.status(503).json({error:'OAuth is not configured.'}); const state=crypto.randomBytes(24).toString('base64url'); pending.add(state); return res.redirect(createOAuthClient(config).generateAuthUrl({access_type:'offline',scope:[YOUTUBE_READ_SCOPE],state,prompt:'consent'})); });
app.get('/auth/google/callback',async(req,res)=>{ const code=typeof req.query.code==='string'?req.query.code:undefined; const state=typeof req.query.state==='string'?req.query.state:undefined; if(req.query.error)return res.status(400).json({error:'Google OAuth authorization was denied or failed.'}); if(!code||!state||!pending.delete(state))return res.status(400).json({error:'Invalid or expired OAuth callback.'}); if(!config.encryptionKey)return res.status(503).json({error:'Token encryption is not configured.'}); try { const oauth=createOAuthClient(config); oauth.setCredentials((await oauth.getToken(code)).tokens); const user=await ingestYouTubeUser(repository,oauth,config.encryptionKey); setUserCookie(res,user.id); return res.json({user:{id:user.id,displayName:user.displayName},ingested:true}); } catch { return res.status(502).json({error:'YouTube ingestion failed. Check granted scope, credentials, quota, and database connectivity.'}); }});
app.get('/api/me',requireUser,async(_req,res)=>res.json({user:await repository.getUser(res.locals.userId)})); app.get('/api/me/subscriptions',requireUser,async(_req,res)=>res.json({subscriptions:await repository.getSubscriptions(res.locals.userId)})); app.get('/api/me/liked-videos',requireUser,async(_req,res)=>res.json({likedVideos:await repository.getLikedVideos(res.locals.userId)})); app.get('/api/me/playlists',requireUser,async(_req,res)=>res.json({playlists:await repository.getPlaylists(res.locals.userId)})); app.get('/api/me/status',requireUser,async(_req,res)=>res.json({authenticated:true,demoMode:config.demoMode,activityImport:'not implemented; optional adapter only'}));
app.use((_error:unknown,_req:Request,res:Response,_next:NextFunction)=>res.status(500).json({error:'Internal service error.'}));
app.listen(config.port,()=>console.log(`Phase 1 server listening on http://localhost:${config.port}`));
